# Pre-commit hooks
repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v6.0.0"
    hooks:
      - id: "trailing-whitespace"
      - id: "end-of-file-fixer"
      - id: "detect-private-key"
      - id: "check-toml"
      - id: "check-executables-have-shebangs"

  # Secrets and sensitive detection
  - repo: "https://github.com/gitleaks/gitleaks"
    rev: "v8.18.3"
    hooks:
      - id: "gitleaks"

  # Shell Check
  - repo: "https://github.com/Anadea/pre-commit-config-shellcheck"
    rev: "0.3.4"
    hooks:
      - id: "pre-commit-config-shellcheck"
